export { AddIcon } from './add-icon'
export { FeedIcon } from './feed-icon'
export { LogoutIcon } from './logout-icon'
export { SendIcon } from './send-icon'
export { StatisticsIcon } from './statistic-icon'
